[package]
name = "special"
version = "0.2.0"
authors = [
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
  "Rúnar Berg Baugsson Sigríðarson <runarberg@zoho.com>",
]
license = "MIT"
repository = "https://github.com/stainless-steel/special"
homepage = "https://github.com/stainless-steel/special"
documentation = "https://stainless-steel.github.io/special"
description = "The library provides special functions."

[dependencies]
libc = "*"
num = "*"

[dev-dependencies]
assert = "*"
rand = "*"
