[package]
name = "sfunc"
version = "0.0.2"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/sfunc"
homepage = "https://github.com/stainless-steel/sfunc"
documentation = "https://stainless-steel.github.io/sfunc"
description = "The library provides special functions."

[dev-dependencies]
assert = "0.0.2"
