[package]
name = "special"
version = "0.1.3"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/special"
homepage = "https://github.com/stainless-steel/special"
documentation = "https://stainless-steel.github.io/special"
description = "The library provides special functions."

[dev-dependencies]
assert = "0.1"
